### PR TITLE
#24 For PHP version >= 7.4.0 look for the properties explicit type declaration first

### LINKED ISSUE #24: Explicit type declarations is not handled!
Since [PHP 7.4 type declarations were introduced](https://www.php.net/manual/en/language.types.declarations.php).

But php-avro-schema-generator does not look in it.

Steps to reproduce:
```php
// in ../DAO/DemoNotification.php
class DemoNotification {
    private string $content;

    public function __construct(string $content) {
        $this->content = $content;
    }

    public function getContent(): string {
        return $this->content;
    }
}

$data = new DemoNotification("Hello");
$registry = (new ClassRegistry())
    ->addClassDirectory(__DIR__ . '/../DAO')
    ->load();
$generator = new SchemaGenerator($registry, '');
$schemas = $generator->generate();
echo(current($schemas)); // Out: {"type":"record","name":"DemoNotification","namespace":"App.DAO","fields":[{"name":"content","type":""}]}
```

## Actual behavior
Despite explicit type declaration:
```
private string $content;
```
Script outputs:
```json
{"type":"record","name":"DemoNotification","namespace":"App.DAO","fields":[{"name":"content","type":""}]}
```

## Expected behavior
```json
{"type":"record","name":"DemoNotification","namespace":"App.DAO","fields":[{"name":"content","type":"string"}]}
```

### PR DESCRIPTION
**Pull request by Hubbitus**
Closes #24

### CODE REVIEW

File: src/Parser/TokenParser.php [hunk 1]
```diff
@@ -199,11 +199,17 @@ public function getProperties(string $classPath): array
      */
     public function getPropertyClass(ReflectionProperty $property, bool $ignorePrimitive = true)
     {
-        // Get the content of the @var annotation
-        if (preg_match('/@var\s+([^\s]+)/', (string) $property->getDocComment(), $matches)) {
-            list(, $type) = $matches;
-        } else {
-            return null;
+        $type = null;
+        if (version_compare(phpversion(), '7.4.0', '>=')) { // Get is explicit type decralation if possible
```
Comment (nick-zh) [inline src/Parser/TokenParser.php:203]:
```suggestion
        // Get is explicit type decralation if possible
        if (version_compare(phpversion(), '7.4.0', '>=') && null !== $property->getType()) {
```

File: src/Parser/TokenParser.php [hunk 2]
```diff
@@ -199,11 +199,17 @@ public function getProperties(string $classPath): array
...
+            $type = $property->getType()->getName();
+        }
+
+        if (is_null($type)){ // Try get the content of the @var annotation
```
Comment (nick-zh) [inline src/Parser/TokenParser.php:207]:
```suggestion
        if (is_null($type)) { // Try get the content of the @var annotation
```
fixes cs complaint
